# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PILSNER DEV
email: darkrasid@nate.com
description: > 
baseurl: "/pilsner" # the subpath of your site, e.g. /blog
url: "http://darkrasid.github.io/" # the base hostname & protocol for your site
github_username:  darkrasid

# Build settings
# markdown: kramdown
markdown: redcarpet



# pilsner: "<div class='author'>
#             <div class='div-img'>
#               <span class='vertical-helper'></span>
#               <img src='https://avatars0.githubusercontent.com/u/3003871?v=3&amp;s=460' alt='pilsner'>
#             </div>
#             <div class='author-info'>
#               <div class='author-name'>Pilsner</div>
#               <div class='author-desc'>맥주랑 연관된 것 같지만 사실은 맥주 잘 모릅니다.</div>
#             </div>
#           </div>"
#
#
